### ISSUE TITLE
add-task-subtasks: make function smaller

### ISSUE THREAD

**Issue by sebmontag** [seb887/da-join#93]
- [x] add new functions (Seb)
- [x] add js docs (Felix)
   - [x] function styleEditSingleSubtask(index, inputEditSubtask)
   - [x] function controlSubtaskIsEditStatus()
   - [x] function styleSubmitEditedSingleSubtask(index, inputEditSubtask)
